'use strict';
var seqMaxRpm=1000,seqLastCompile=null,seqPollTimer=null;
function commandOk(response,label){return String(response).toLowerCase().indexOf(String(label).toLowerCase()+': ok')>=0}
async function seqRefreshMaxRpm(){if(!writer&&!simMode)return;try{var r=await send('param get max_wheel_rpm'),m=String(r).match(/max_wheel_rpm\s*=\s*(\d+)/);if(m)seqMaxRpm=Math.max(1,Number(m[1]));render();edit()}catch(e){}}
function seqShowNotice(message,type){var el=$('seqNotice');if(!el)return;el.textContent=message;el.className=type||'';clearTimeout(el._timer);el._timer=setTimeout(function(){el.textContent='';el.className=''},3500)}
function seqField(label,key,type,options,help){var n=seqNode(seqSelectedNode),v=n.params[key],html='<label>'+label+'</label>';if(type==='select')html+='<select class="seq-prop" data-key="'+key+'">'+options.map(function(o){return'<option value="'+o.value+'"'+(String(o.value)===String(v)?' selected':'')+'>'+o.label+'</option>'}).join('')+'</select>';else html+='<div class="seq-input-unit"><input class="seq-prop" data-key="'+key+'" type="number" min="'+options.min+'" max="'+options.max+'" step="'+(options.step||1)+'" value="'+v+'"><span>'+options.unit+'</span></div>';if(help)html+='<small>'+help+'</small>';return html}
function seqConditionOptions(type){return SC.conditionAllowed(type).map(function(c){return{value:c,label:SC.COND_LABELS[c]+' ('+c+')'}})}
function seqProperties(n){var h='';if(n.type==='drive')h+=seqField('目标转速','rpm','number',{min:-seqMaxRpm,max:seqMaxRpm,unit:'RPM'},'正数前进，负数后退。')+seqField('完成条件','condition','select',seqConditionOptions(n.type))+seqField('安全时间','timeoutMs','number',{min:1,max:30000,unit:'ms'},'定时条件下是运行时间，其他条件下是安全超时。');else if(n.type==='drive_mm')h+=seqField('行驶距离','distanceMm','number',{min:-10000,max:10000,unit:'mm'},'正数前进，负数后退，不能为 0。')+seqField('最大转速','maxRpm','number',{min:1,max:seqMaxRpm,unit:'RPM'});else if(n.type==='turn')h+=seqField('相对转角','angleDeg','number',{min:-180,max:180,unit:'°'},'正数左转，负数右转。')+seqField('安全超时','timeoutMs','number',{min:1,max:30000,unit:'ms'});else if(n.type==='follow')h+=seqField('基础转速','rpm','number',{min:-seqMaxRpm,max:seqMaxRpm,unit:'RPM'})+seqField('完成条件','condition','select',seqConditionOptions(n.type))+seqField('安全时间','timeoutMs','number',{min:1,max:30000,unit:'ms'});else if(n.type==='wait')h+=seqField('等待条件','condition','select',seqConditionOptions(n.type))+seqField('最长等待','timeoutMs','number',{min:0,max:30000,unit:'ms'});else if(n.type==='branch')h+=seqField('判断条件','condition','select',seqConditionOptions(n.type),'条件立即采样，不成立时走红色端口。');else if(n.type.indexOf('led_')===0){h+=seqField('LED 目标','target','select',[{value:0,label:'LED2 + LED3'},{value:2,label:'仅 LED2'},{value:3,label:'仅 LED3'}]);if(n.type!=='led_off')h+=seqField('自动关闭','durationMs','number',{min:0,max:30000,unit:'ms'},'0 表示保持；非零时最少 50 ms。')}else if(n.type==='buzzer_on'||n.type==='buzzer_toggle')h+=seqField('自动关闭','durationMs','number',{min:0,max:30000,unit:'ms'},'0 表示保持；非零时最少 50 ms。');else h+='<p class="seq-muted">该动作没有可调参数。</p>';return h}
function edit(){var el=$('editorContent');if(!el||!seqProject)return;var validation=SC.validate(seqProject,{maxRpm:seqMaxRpm}),node=seqNode(seqSelectedNode);if(seqSelectedEdge){el.innerHTML='<div class="seq-panel-title">连线</div><p class="seq-muted">选中连线后可按 Delete 删除，也可从同一端口重新拖线。</p><button class="danger" id="btnDeleteEdge">删除连线</button>';var de=$('btnDeleteEdge');if(de)de.onclick=seqDeleteSelection;return}if(!node){var errs=validation.issues;el.innerHTML='<div class="seq-panel-title">流程检查</div><div class="seq-project-meta"><b>'+seqEsc(seqProject.name)+'</b><span>绑定槽位 '+seqProject.slot+' · '+seqProject.nodes.filter(function(n){return SC.ACTIONS[n.type]}).length+' 步</span></div><div class="seq-issues">'+(errs.length?errs.map(function(i){return'<button class="seq-issue '+i.severity+'" data-node="'+(i.nodeId||'')+'">'+(i.severity==='error'?'错误':'提醒')+' · '+seqEsc(i.message)+'</button>'}).join(''):'<div class="seq-pass">✓ 参数、连线和可达性检查通过</div>')+'</div><div class="seq-help"><b>端口说明</b><p>绿色是动作完成路径；红色是失败或超时路径。失败端口不连时默认中止，分支的两个端口都必须连接。</p><b>试运行与保存</b><p>“试运行当前画布”只临时写入 RAM；“保存到 FRAM”才会覆盖所选槽位。</p></div>';el.querySelectorAll('.seq-issue[data-node]').forEach(function(x){x.onclick=function(){if(x.dataset.node)seqSelectNode(x.dataset.node)}});return}if(node.type.indexOf('system_')===0){el.innerHTML='<div class="seq-panel-title">'+(node.type==='system_start'?'开始节点':'中止节点')+'</div><p class="seq-muted">'+(node.type==='system_start'?'所有可执行动作必须从这里可达。':'失败路径连接到这里会编译为 ontimeout=abort。')+'</p>';return}var a=SC.ACTIONS[node.type],nodeIssues=validation.issues.filter(function(i){return i.nodeId===node.id});el.innerHTML='<div class="seq-panel-title">'+a.name+'</div><div class="seq-tech">Shell: '+node.type+' · ActionOp '+a.op+'</div><p class="seq-action-help">'+a.help+'</p>'+seqProperties(node)+(nodeIssues.length?'<div class="seq-inline-errors">'+nodeIssues.map(function(i){return'<p class="'+i.severity+'">'+seqEsc(i.message)+'</p>'}).join('')+'</div>':'')+'<div class="btn-row"><button id="btnDuplicateNode">复制</button><button id="btnDeleteNode" class="danger">删除</button></div>';
 el.querySelectorAll('.seq-prop').forEach(function(input){input.onchange=function(){var before=seqSnapshot(),key=input.dataset.key,value=input.tagName==='SELECT'?input.value:Number(input.value);node.params[key]=value;seqCommit('已更新“'+a.name+'”参数',before)}});$('btnDuplicateNode').onclick=seqDuplicate;$('btnDeleteNode').onclick=seqDeleteSelection}
function seqRawEqual(a,b){if(a.length!==b.length)return false;return a.every(function(x,i){var y=b[i];return['op','p1','p2','until','ons','ont'].every(function(k){return Number(x[k])===Number(y[k])})})}
function seqParseRunDump(text){var lines=String(text).split(/\r?\n/),out=[];lines.forEach(function(l){var p=l.trim().split(/\s+/);if(p.length>=7&&/^\d+$/.test(p[0])){var op=Object.keys(OP).find(function(k){return OP[k]===p[1]});out.push({op:Number(op),p1:Number(p[2]),p2:Number(p[3]),until:COND.indexOf(p[4]),ons:Number(p[5]),ont:Number(p[6])})}});return out}
async function seqUpload(instrs){var r=await send('run clear');if(!commandOk(r,'run clear'))throw new Error('清空 RAM 表失败');for(var i=0;i<instrs.length;i++){var x=instrs[i],cmd='run add '+OP[x.op]+' '+x.p1+' '+x.p2+' '+COND[x.until]+' '+(x.ons===255?'next':x.ons)+' '+(x.ont===255?'abort':x.ont);r=await send(cmd);if(!commandOk(r,'run add'))throw new Error('第 '+i+' 步下发失败：'+r.trim())}r=await send('run validate');if(!/run validate ok/i.test(r))throw new Error('固件校验失败：'+r.trim());var back=seqParseRunDump(await send('run dump'));if(!seqRawEqual(instrs,back))throw new Error('RAM 回读内容与画布编译结果不一致');return true}
async function seqRestoreRam(raw){try{if(raw&&raw.length)await seqUpload(raw);else await send('run clear')}catch(e){logc('tx','[RAM RESTORE FAILED] '+e.message)}}
function seqCompileCurrent(){seqLastCompile=SC.compile(seqProject,{maxRpm:seqMaxRpm});return seqLastCompile}
async function runSlot(){if((!writer&&!simMode)||!seqProject){seqShowNotice('请先连接串口或开启模拟模式','error');return}var backup=[];try{var compiled=seqCompileCurrent();backup=seqParseRunDump(await send('run dump'));await seqUpload(compiled.instrs);var start=await send('run start');if(!commandOk(start,'run start'))throw new Error('启动失败：'+start.trim());seqShowNotice('当前画布已在 RAM 中启动，未写入 FRAM','ok');seqStartPolling()}catch(e){await seqRestoreRam(backup);seqShowNotice(e.message,'error');logc('tx','[试运行失败] '+e.message)}}
async function saveSlot(){if((!writer&&!simMode)||!seqProject){seqShowNotice('请先连接串口或开启模拟模式','error');return}var slot=Number(seqProject.slot);if(slots[slot]&&slots[slot].length&&!window.confirm('槽位 '+slot+' 已有 '+slots[slot].length+' 步，确认覆盖 FRAM？'))return;try{var compiled=seqCompileCurrent();await seqUpload(compiled.instrs);var r=await send('seq save '+slot);if(!commandOk(r,'seq save'))throw new Error('FRAM 保存失败');var back=parse(await send('seq dump '+slot));if(!seqRawEqual(compiled.instrs,back))throw new Error('FRAM 保存后的回读比对失败');slots[slot]=back;seqShowNotice('已保存到 FRAM 槽位 '+slot+'，并通过回读比对','ok');await refreshSlots()}catch(e){seqShowNotice(e.message,'error');logc('tx','[保存失败] '+e.message)}}
function seqParseStatus(text){var m=String(text).match(/run\s+(\d+)\/(\d+)\s+running=(\d).*?result=([^\s]+)/s);return m?{current:+m[1],count:+m[2],running:m[3]==='1',result:m[4]}:null}
function seqStartPolling(){clearInterval(seqPollTimer);seqPollTimer=setInterval(async function(){try{var s=seqParseStatus(await send('run status'));if(!s)return;if(seqLastCompile&&s.current<seqLastCompile.nodeOrder.length)seqActiveNode=seqLastCompile.nodeOrder[s.current];else seqActiveNode=null;render();if(!s.running){clearInterval(seqPollTimer);seqPollTimer=null;seqShowNotice(s.result==='success'?'序列执行完成':'序列已停止：'+s.result,s.result==='success'?'ok':'error')}}catch(e){}},500)}
async function seqEmergencyStop(){clearInterval(seqPollTimer);seqPollTimer=null;seqActiveNode=null;render();if(!writer&&!simMode){seqShowNotice('当前未连接设备','error');return}var commands=['run cancel','comp stop','heading stop','lf stop','chassis stop'];for(var i=0;i<commands.length;i++){try{await send(commands[i],{timeoutMs:700})}catch(e){}}seqShowNotice('已发送序列、比赛、航向、循迹和底盘停止命令','error')}
function seqDownload(){var blob=new Blob([SC.serialize(seqProject)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(seqProject.name||'gugapi-sequence').replace(/[\\/:*?"<>|]/g,'_')+'.json';a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},1000)}
function seqBindUi(){seqBuildPalette();seqInitCanvas();$('btnSeqUndo').onclick=seqUndo;$('btnSeqRedo').onclick=seqRedo;$('btnSeqFit').onclick=seqFit;$('btnSeqLayout').onclick=seqAutoLayout;$('btnSeqNew').onclick=function(){if(window.confirm('新建工程会替换当前本地画布，继续吗？'))setSeqProject(SC.newProject('未命名流程',curSlot>=0?curSlot:7))};$('btnSeqExport').onclick=seqDownload;$('btnSeqImport').onclick=function(){$('seqFileInput').click()};$('seqFileInput').onchange=async function(){try{var text=await this.files[0].text();setSeqProject(SC.normalizeProject(JSON.parse(text)));seqShowNotice('工程导入成功','ok')}catch(e){seqShowNotice('导入失败：'+e.message,'error')}this.value=''};$('seqProjectName').onchange=function(){var before=seqSnapshot();seqProject.name=this.value.trim()||'未命名流程';seqCommit('已修改工程名称',before)};$('seqProjectSlot').onchange=function(){var before=seqSnapshot();seqProject.slot=Number(this.value);curSlot=seqProject.slot;seqCommit('已绑定槽位 '+seqProject.slot,before)};$('seqTemplate').onchange=function(){if(this.value==='')return;var p=SC.templates()[Number(this.value)];if(p){p.slot=seqProject.slot;setSeqProject(p);seqShowNotice('已载入模板“'+p.name+'”','ok')}this.value=''};$('btnSeqRun').onclick=runSlot;$('btnSeqSave').onclick=saveSlot;$('btnEmergencyStop').onclick=seqEmergencyStop;$('btnSeqHelp').onclick=function(){$('seqGuide').classList.add('show')};$('btnGuideClose').onclick=function(){$('seqGuide').classList.remove('show');localStorage.setItem('gugapi-seq-guide-seen','1')};var saved=localStorage.getItem(seqStorageKey());try{setSeqProject(saved?JSON.parse(saved):SC.templates()[0])}catch(e){setSeqProject(SC.templates()[0])}if(!localStorage.getItem('gugapi-seq-guide-seen'))$('seqGuide').classList.add('show')}
var oldRender=render;render=function(){oldRender();if(seqProject){$('seqProjectName').value=seqProject.name;$('seqProjectSlot').value=String(seqProject.slot)}};
seqBindUi();
seqFixWirePointerEvents();
