const EDIT_OPS=[1,2,3,4,5,6,7,8,9,10,11,12,13,14];
function isLedOp(op){return op>=9&&op<=11}
function isBuzzerOp(op){return op>=12&&op<=14}
function isOutputOp(op){return isLedOp(op)||isBuzzerOp(op)}
function isOffOp(op){return op===10||op===13}
function editorParams(ins){
  if(isLedOp(ins.op)){return'<label>LED Target</label><select id="eP1"><option value="0"'+(ins.p1===0?' selected':'')+'>LED2 + LED3</option><option value="2"'+(ins.p1===2?' selected':'')+'>LED2</option><option value="3"'+(ins.p1===3?' selected':'')+'>LED3</option></select>'+(isOffOp(ins.op)?'<input id="eP2" type="hidden" value="0">':'<label>Auto-off (ms, 0=persistent)</label><input id="eP2" type="number" min="0" max="30000" value="'+ins.p2+'"><small>Use 0 or 50–30000 ms</small>')}
  if(isBuzzerOp(ins.op)){return'<input id="eP1" type="hidden" value="0">'+(isOffOp(ins.op)?'<input id="eP2" type="hidden" value="0">':'<label>Auto-off (ms, 0=persistent)</label><input id="eP2" type="number" min="0" max="30000" value="'+ins.p2+'"><small>Use 0 or 50–30000 ms</small>')}
  if(ins.op===8){return'<label>Distance (signed mm)</label><input id="eP1" type="number" min="-10000" max="10000" value="'+ins.p1+'"><label>Maximum RPM</label><input id="eP2" type="number" min="1" value="'+ins.p2+'">'}
  return'<label>Param1 (RPM/deg)</label><input id="eP1" type="number" value="'+ins.p1+'"><label>Param2 (ms)</label><input id="eP2" type="number" value="'+ins.p2+'">'
}
function editorUntil(ins){if(isOutputOp(ins.op))return'<input id="eUntil" type="hidden" value="5"><label>Until</label><input value="immediate" disabled>';if(ins.op===8)return'<input id="eUntil" type="hidden" value="6"><label>Until</label><input value="distance_reached" disabled>';return'<label>Until</label><select id="eUntil">'+COND.map(function(c,i){return'<option value="'+i+'"'+(ins.until===i?' selected':'')+'>'+c+'</option>'}).join('')+'</select>'}
function changeOp(){if(selIdx<0)return;var op=+$('eOp').value;var ins=instrs[selIdx];ins.op=op;if(isOutputOp(op)){ins.p1=isBuzzerOp(op)?0:(ins.p1===2||ins.p1===3?ins.p1:0);ins.p2=isOffOp(op)?0:ins.p2;ins.until=5}else if(op===8){ins.p1=ins.p1||100;ins.p2=ins.p2||60;ins.until=6}edit()}
function edit(){var el=$('editorContent');
  if(!port&&!simMode){el.innerHTML='Connect first';el.style.opacity=0.4;return}
  if(curSlot<0){el.innerHTML='Select a slot';el.style.opacity=0.4;return}
  el.style.opacity=1;
  if(selIdx<0){el.innerHTML='<p style="opacity:0.6;margin-bottom:10px">Slot '+curSlot+': '+instrs.length+' instructions</p><button class="primary" onclick="addI()">+ Add</button><hr style="border-color:#45475a;margin:12px 0"><div class="btn-row"><button onclick="saveSlot()">Save to '+curSlot+'</button><button class="danger" onclick="runSlot()">Test Run</button></div>';return}
  var ins=instrs[selIdx];
  el.innerHTML='<p style="opacity:0.6;margin-bottom:8px">Edit #'+selIdx+'</p><label>Op</label><select id="eOp" onchange="changeOp()">'+EDIT_OPS.map(function(o){return'<option value="'+o+'"'+(ins.op===o?' selected':'')+'>'+OPL[o]+'</option>'}).join('')+'</select>'+editorParams(ins)+editorUntil(ins)+'<label>On Success</label><select id="eOns"><option value="255"'+(ins.ons===255?' selected':'')+'>next</option>'+instrs.map(function(_,i){return'<option value="'+i+'"'+(ins.ons===i?' selected':'')+'>goto '+i+'</option>'}).join('')+'</select><label>On Timeout</label><select id="eOnt"><option value="255"'+(ins.ont===255?' selected':'')+'>abort</option>'+instrs.map(function(_,i){return'<option value="'+i+'"'+(ins.ont===i?' selected':'')+'>goto '+i+'</option>'}).join('')+'</select><div class="btn-row"><button class="primary" onclick="applyE()">Apply</button><button onclick="addI()">+ Add</button><button class="danger" onclick="delI()">Del</button></div><div class="btn-row"><button onclick="moveI(-1)">Up</button><button onclick="moveI(1)">Down</button></div><hr style="border-color:#45475a;margin:12px 0"><div class="btn-row"><button onclick="saveSlot()">Save to '+curSlot+'</button><button class="danger" onclick="runSlot()">Test Run</button></div>'}
function applyE(){if(selIdx<0)return;var op=+$('eOp').value;instrs[selIdx].op=op;instrs[selIdx].p1=isBuzzerOp(op)?0:(+$('eP1').value||0);instrs[selIdx].p2=isOffOp(op)?0:(+$('eP2').value||0);instrs[selIdx].until=isOutputOp(op)?5:(op===8?6:+$('eUntil').value);instrs[selIdx].ons=+$('eOns').value;instrs[selIdx].ont=+$('eOnt').value;render();edit()}
function addI(){instrs.splice(selIdx+1,0,{op:1,p1:60,p2:2000,until:0,ons:255,ont:255});selIdx++;render();edit()}
function delI(){if(selIdx<0)return;instrs.splice(selIdx,1);selIdx=-1;render();edit()}
function moveI(d){var n=selIdx+d;if(n<0||n>=instrs.length)return;var t=instrs[selIdx];instrs[selIdx]=instrs[n];instrs[n]=t;selIdx=n;render();edit()}
function commandOk(response,label){return String(response).toLowerCase().indexOf(label.toLowerCase()+': ok')>=0}
async function saveSlot(){if((!writer&&!simMode)||curSlot<0)return;try{if(selIdx>=0&&$('eOp'))applyE();var response=await send('run clear');if(!commandOk(response,'run clear'))throw new Error('run clear failed');for(var i=0;i<instrs.length;i++){var ins=instrs[i];var ons=ins.ons===255?'next':ins.ons;var ont=ins.ont===255?'abort':ins.ont;response=await send('run add '+OP[ins.op]+' '+ins.p1+' '+ins.p2+' '+COND[ins.until]+' '+ons+' '+ont);if(!commandOk(response,'run add'))throw new Error('run add #'+i+' failed')}response=await send('seq save '+curSlot);if(!commandOk(response,'seq save'))throw new Error('seq save failed');logc('tx','[SAVED to slot '+curSlot+']');slots[curSlot]=instrs.map(function(x){return Object.assign({},x)})}catch(error){logc('tx','[SAVE FAILED] '+error.message)}}
async function runSlot(){if((!writer&&!simMode)||curSlot<0)return;try{var status=await send('comp status');if(/\bmode=running\b/i.test(status))throw new Error('competition task is already running');var command=/\bmode=armed\b/i.test(status)?'comp start '+curSlot:'seq run '+curSlot;var response=await send(command);var label=command.startsWith('comp ')?'comp start':'seq run';if(!commandOk(response,label))throw new Error(label+' failed');logc('tx','[RUNNING slot '+curSlot+']')}catch(error){logc('tx','[RUN FAILED] '+error.message)}}
$('btnRefresh').onclick=refreshSlots;
