function edit(){var el=$('editorContent');
  if(!port&&!simMode){el.innerHTML='Connect first';el.style.opacity=0.4;return}
  if(curSlot<0){el.innerHTML='Select a slot';el.style.opacity=0.4;return}
  el.style.opacity=1;
  if(selIdx<0){el.innerHTML='<p style="opacity:0.6;margin-bottom:10px">Slot '+curSlot+': '+instrs.length+' instructions</p><button class="primary" onclick="addI()">+ Add</button><hr style="border-color:#45475a;margin:12px 0"><div class="btn-row"><button onclick="saveSlot()">Save to '+curSlot+'</button><button class="danger" onclick="runSlot()">Test Run</button></div>';return}
  var ins=instrs[selIdx];
  el.innerHTML='<p style="opacity:0.6;margin-bottom:8px">Edit #'+selIdx+'</p><label>Op</label><select id="eOp">'+[1,2,3,4,5,6,7].map(function(o){return'<option value="'+o+'"'+(ins.op===o?' selected':'')+'>'+OPL[o]+'</option>'}).join('')+'</select><label>Param1 (RPM/deg)</label><input id="eP1" type="number" value="'+ins.p1+'"><label>Param2 (ms)</label><input id="eP2" type="number" value="'+ins.p2+'"><label>Until</label><select id="eUntil">'+COND.map(function(c,i){return'<option value="'+i+'"'+(ins.until===i?' selected':'')+'>'+c+'</option>'}).join('')+'</select><label>On Success</label><select id="eOns"><option value="255"'+(ins.ons===255?' selected':'')+'>next</option>'+instrs.map(function(_,i){return'<option value="'+i+'"'+(ins.ons===i?' selected':'')+'>goto '+i+'</option>'}).join('')+'</select><label>On Timeout</label><select id="eOnt"><option value="255"'+(ins.ont===255?' selected':'')+'>abort</option>'+instrs.map(function(_,i){return'<option value="'+i+'"'+(ins.ont===i?' selected':'')+'>goto '+i+'</option>'}).join('')+'</select><div class="btn-row"><button class="primary" onclick="applyE()">Apply</button><button onclick="addI()">+ Add</button><button class="danger" onclick="delI()">Del</button></div><div class="btn-row"><button onclick="moveI(-1)">Up</button><button onclick="moveI(1)">Down</button></div><hr style="border-color:#45475a;margin:12px 0"><div class="btn-row"><button onclick="saveSlot()">Save to '+curSlot+'</button><button class="danger" onclick="runSlot()">Test Run</button></div>'}
function applyE(){if(selIdx<0)return;instrs[selIdx].op=+$('eOp').value;instrs[selIdx].p1=+$('eP1').value||0;instrs[selIdx].p2=+$('eP2').value||0;instrs[selIdx].until=+$('eUntil').value;instrs[selIdx].ons=+$('eOns').value;instrs[selIdx].ont=+$('eOnt').value;render();edit()}
function addI(){instrs.splice(selIdx+1,0,{op:1,p1:60,p2:2000,until:0,ons:255,ont:255});selIdx++;render();edit()}
function delI(){if(selIdx<0)return;instrs.splice(selIdx,1);selIdx=-1;render();edit()}
function moveI(d){var n=selIdx+d;if(n<0||n>=instrs.length)return;var t=instrs[selIdx];instrs[selIdx]=instrs[n];instrs[n]=t;selIdx=n;render();edit()}
async function saveSlot(){if((!writer&&!simMode)||curSlot<0)return;await send('run clear');for(var i=0;i<instrs.length;i++){var ins=instrs[i];var ons=ins.ons===255?'next':ins.ons;var ont=ins.ont===255?'abort':ins.ont;await send('run add '+OP[ins.op]+' '+ins.p1+' '+ins.p2+' '+COND[ins.until]+' '+ons+' '+ont)}await send('seq save '+curSlot);logc('tx','[SAVED to slot '+curSlot+']');slots[curSlot]=instrs.map(function(x){return Object.assign({},x)})}
async function runSlot(){if((!writer&&!simMode)||curSlot<0)return;await send('seq run '+curSlot);logc('tx','[RUNNING slot '+curSlot+']')}
$('btnRefresh').onclick=refreshSlots;
