#ifndef BOARD_BOARD_PINS_H_
#define BOARD_BOARD_PINS_H_

#include "ti_msp_dl_config.h"

/*
 * 自定义板级引脚归属表。
 * 新外设先在这里增加板级别名，再由 SysConfig 生成最终的引脚复用代码，
 * 避免驱动层硬编码具体板子的管脚。
 */

#define BOARD_PIN_SWDIO_PORT            GPIOA
#define BOARD_PIN_SWDIO_PIN             DL_GPIO_PIN_19

#define BOARD_PIN_SWCLK_PORT            GPIOA
#define BOARD_PIN_SWCLK_PIN             DL_GPIO_PIN_20

#define BOARD_STATUS_LED_PORT           GPIO_LEDS_PORT
#define BOARD_STATUS_LED_PIN            GPIO_LEDS_STATUS_LED_PIN
#define BOARD_STATUS_LED_ACTIVE_LOW     (1U)
#define BOARD_STATUS_LED_INITIAL_ON     (0U)

#define BOARD_BUZZER_PORT               GPIO_BUZZER_PORT
#define BOARD_BUZZER_PIN                GPIO_BUZZER_BUZZER_PIN
#define BOARD_BUZZER_ACTIVE_HIGH        (1U)
#define BOARD_BUZZER_INITIAL_ON         (0U)

#define BOARD_BUTTON1_PORT              GPIO_BUTTON_C_PORT
#define BOARD_BUTTON1_PIN               GPIO_BUTTON_C_BUTTON1_PIN
#define BOARD_BUTTON2_PORT              GPIO_BUTTON_B_PORT
#define BOARD_BUTTON2_PIN               GPIO_BUTTON_B_BUTTON2_PIN
#define BOARD_BUTTON3_PORT              GPIO_BUTTON_B_PORT
#define BOARD_BUTTON3_PIN               GPIO_BUTTON_B_BUTTON3_PIN
#define BOARD_BUTTON_ACTIVE_LOW         (1U)
#define BOARD_BUTTON_DEBOUNCE_MS        (20U)

/* LoRa 串口透传：芯片封装 20 脚 PB0/UART0_TX 接 LoRa RX，21 脚 PB1/UART0_RX 接 LoRa TX。 */
#define BOARD_LORA_UART_INST            LORA_UART_INST
#define BOARD_LORA_UART_IRQN            LORA_UART_INST_INT_IRQN
#define BOARD_LORA_TX_PORT              GPIO_LORA_UART_TX_PORT
#define BOARD_LORA_TX_PIN               GPIO_LORA_UART_TX_PIN
#define BOARD_LORA_RX_PORT              GPIO_LORA_UART_RX_PORT
#define BOARD_LORA_RX_PIN               GPIO_LORA_UART_RX_PIN
#define BOARD_LORA_BAUDRATE             (115200U)
#define BOARD_LORA_RX_BUFFER_SIZE       (256U)
#define BOARD_LORA_TX_TIMEOUT_ITERATIONS (100000U)

/* MotorDriver 串口连接测试：芯片封装 PA8/UART1_TX 接 MotorDriver RX，PA9/UART1_RX 接 MotorDriver TX。 */
#define BOARD_MOTOR_DRIVER_UART_INST            MOTOR_UART_INST
#define BOARD_MOTOR_DRIVER_UART_IRQN            MOTOR_UART_INST_INT_IRQN
#define BOARD_MOTOR_DRIVER_TX_PORT              GPIO_MOTOR_UART_TX_PORT
#define BOARD_MOTOR_DRIVER_TX_PIN               GPIO_MOTOR_UART_TX_PIN
#define BOARD_MOTOR_DRIVER_RX_PORT              GPIO_MOTOR_UART_RX_PORT
#define BOARD_MOTOR_DRIVER_RX_PIN               GPIO_MOTOR_UART_RX_PIN
#define BOARD_MOTOR_DRIVER_BAUDRATE             (115200U)
#define BOARD_MOTOR_DRIVER_RX_BUFFER_SIZE       (256U)
#define BOARD_MOTOR_DRIVER_TX_TIMEOUT_ITERATIONS (100000U)

#define BOARD_FRAM_I2C_INST             FRAM_I2C_INST
#define BOARD_FRAM_I2C_SCL_PORT         GPIO_FRAM_I2C_SCL_PORT
#define BOARD_FRAM_I2C_SCL_PIN          GPIO_FRAM_I2C_SCL_PIN
#define BOARD_FRAM_I2C_SCL_IOMUX        GPIO_FRAM_I2C_IOMUX_SCL
#define BOARD_FRAM_I2C_SCL_IOMUX_FUNC   GPIO_FRAM_I2C_IOMUX_SCL_FUNC
#define BOARD_FRAM_I2C_SDA_PORT         GPIO_FRAM_I2C_SDA_PORT
#define BOARD_FRAM_I2C_SDA_PIN          GPIO_FRAM_I2C_SDA_PIN
#define BOARD_FRAM_I2C_SDA_IOMUX        GPIO_FRAM_I2C_IOMUX_SDA
#define BOARD_FRAM_I2C_SDA_IOMUX_FUNC   GPIO_FRAM_I2C_IOMUX_SDA_FUNC
#define BOARD_FRAM_I2C_ADDRESS          (0x50U)
#define BOARD_FRAM_TIMEOUT_ITERATIONS   (100000U)
#define BOARD_FRAM_SELF_TEST_ADDRESS    (0x1FF0U)

/* INA219：芯片封装 34 脚为 PA11/SCL，33 脚为 PA10/SDA，采样电阻 5mR。 */
#define BOARD_INA219_I2C_INST           INA219_I2C_INST
#define BOARD_INA219_I2C_SCL_PORT       GPIO_INA219_I2C_SCL_PORT
#define BOARD_INA219_I2C_SCL_PIN        GPIO_INA219_I2C_SCL_PIN
#define BOARD_INA219_I2C_SCL_IOMUX      GPIO_INA219_I2C_IOMUX_SCL
#define BOARD_INA219_I2C_SCL_IOMUX_FUNC GPIO_INA219_I2C_IOMUX_SCL_FUNC
#define BOARD_INA219_I2C_SDA_PORT       GPIO_INA219_I2C_SDA_PORT
#define BOARD_INA219_I2C_SDA_PIN        GPIO_INA219_I2C_SDA_PIN
#define BOARD_INA219_I2C_SDA_IOMUX      GPIO_INA219_I2C_IOMUX_SDA
#define BOARD_INA219_I2C_SDA_IOMUX_FUNC GPIO_INA219_I2C_IOMUX_SDA_FUNC
#define BOARD_INA219_I2C_ADDRESS        (0x40U)
#define BOARD_INA219_TIMEOUT_ITERATIONS (100000U)
#define BOARD_INA219_SHUNT_MILLIOHMS    (5U)
#define BOARD_INA219_CURRENT_LSB_UA     (200U)
/* 当前板子 IN+/IN- 方向与期望读数相反，软件取反后 shell 显示为正电流。 */
#define BOARD_INA219_INVERT_CURRENT     (1U)

#define BOARD_IMU_SPI_INST              IMU_SPI_INST
#define BOARD_IMU_SPI_IRQN              IMU_SPI_INST_INT_IRQN
#define BOARD_IMU_SPI_TIMEOUT_ITERATIONS (100000U)
#define BOARD_IMU_SPI_SCLK_PORT         GPIO_IMU_SPI_SCLK_PORT
#define BOARD_IMU_SPI_SCLK_PIN          GPIO_IMU_SPI_SCLK_PIN
#define BOARD_IMU_SPI_PICO_PORT         GPIO_IMU_SPI_PICO_PORT
#define BOARD_IMU_SPI_PICO_PIN          GPIO_IMU_SPI_PICO_PIN
#define BOARD_IMU_SPI_POCI_PORT         GPIO_IMU_SPI_POCI_PORT
#define BOARD_IMU_SPI_POCI_PIN          GPIO_IMU_SPI_POCI_PIN

#define BOARD_IMU_ICM45686_CS_PORT      GPIO_IMU_C_PORT
#define BOARD_IMU_ICM45686_CS_PIN       GPIO_IMU_C_ICM45686_CS_PIN
#define BOARD_IMU_LIS3MDL_CS_PORT       GPIO_IMU_C_PORT
#define BOARD_IMU_LIS3MDL_CS_PIN        GPIO_IMU_C_LIS3MDL_CS_PIN
#define BOARD_IMU_ICM45686_INT1_PORT    GPIO_IMU_C_PORT
#define BOARD_IMU_ICM45686_INT1_PIN     GPIO_IMU_C_ICM45686_INT1_PIN
#define BOARD_IMU_LIS3MDL_DRDY_PORT     GPIO_IMU_A_PORT
#define BOARD_IMU_LIS3MDL_DRDY_PIN      GPIO_IMU_A_LIS3MDL_DRDY_PIN
#define BOARD_IMU_ICM45686_INT2_FSYNC_PORT GPIO_IMU_A_PORT
#define BOARD_IMU_ICM45686_INT2_FSYNC_PIN  GPIO_IMU_A_ICM45686_INT2_FSYNC_PIN

#endif /* BOARD_BOARD_PINS_H_ */
