#ifndef BOARD_BOARD_PINS_H_
#define BOARD_BOARD_PINS_H_

#include "ti_msp_dl_config.h"

/*
 * 自定义板级引脚归属表。
 * 新外设先在这里增加板级别名，再由 SysConfig 生成最终的引脚复用代码，
 * 避免驱动层硬编码具体板子的管脚。
 */

#define BOARD_PIN_SWDIO_PORT            GPIOA
#define BOARD_PIN_SWDIO_PIN             DL_GPIO_PIN_19

#define BOARD_PIN_SWCLK_PORT            GPIOA
#define BOARD_PIN_SWCLK_PIN             DL_GPIO_PIN_20

#define BOARD_LED_COUNT                 (3U)
#define BOARD_LED1_PORT                 GPIO_LED_A_PORT
#define BOARD_LED1_PIN                  GPIO_LED_A_LED1_PIN
#define BOARD_LED1_ACTIVE_LOW           (1U)
#define BOARD_LED1_INITIAL_ON           (0U)
#define BOARD_LED2_PORT                 GPIO_LED_A_PORT
#define BOARD_LED2_PIN                  GPIO_LED_A_LED2_PIN
#define BOARD_LED2_ACTIVE_LOW           (1U)
#define BOARD_LED2_INITIAL_ON           (0U)
#define BOARD_LED3_PORT                 GPIO_LED_B_PORT
#define BOARD_LED3_PIN                  GPIO_LED_B_LED3_PIN
#define BOARD_LED3_ACTIVE_LOW           (1U)
#define BOARD_LED3_INITIAL_ON           (0U)

#define BOARD_STATUS_LED_PORT           BOARD_LED1_PORT
#define BOARD_STATUS_LED_PIN            BOARD_LED1_PIN
#define BOARD_STATUS_LED_ACTIVE_LOW     BOARD_LED1_ACTIVE_LOW
#define BOARD_STATUS_LED_INITIAL_ON     BOARD_LED1_INITIAL_ON

#define BOARD_BUZZER_PORT               GPIO_BUZZER_PORT
#define BOARD_BUZZER_PIN                GPIO_BUZZER_BUZZER_PIN
#define BOARD_BUZZER_ACTIVE_HIGH        (1U)
#define BOARD_BUZZER_INITIAL_ON         (0U)

/* GY931 angle sensor uses GPIO bit-banged I2C on PA29/SCL and PA30/SDA. */
#define BOARD_GY931_I2C_SCL_PORT        GPIO_GY931_I2C_PORT
#define BOARD_GY931_I2C_SCL_PIN         GPIO_GY931_I2C_GY931_SCL_PIN
#define BOARD_GY931_I2C_SCL_IOMUX       GPIO_GY931_I2C_GY931_SCL_IOMUX
#define BOARD_GY931_I2C_SDA_PORT        GPIO_GY931_I2C_PORT
#define BOARD_GY931_I2C_SDA_PIN         GPIO_GY931_I2C_GY931_SDA_PIN
#define BOARD_GY931_I2C_SDA_IOMUX       GPIO_GY931_I2C_GY931_SDA_IOMUX
#define BOARD_GY931_I2C_ADDRESS         (0x50U)
/* Software I2C timing is expressed in physical time and converted by the
 * common time service, so changing CPUCLK does not change the bus waveform. */
#define BOARD_GY931_I2C_HALF_PERIOD_US  (4U)
#define BOARD_GY931_I2C_TIMEOUT_CYCLES  (100000U)

#define BOARD_BUTTON1_PORT              GPIO_BUTTON_C_PORT
#define BOARD_BUTTON1_PIN               GPIO_BUTTON_C_BUTTON1_PIN
#define BOARD_BUTTON2_PORT              GPIO_BUTTON_B_PORT
#define BOARD_BUTTON2_PIN               GPIO_BUTTON_B_BUTTON2_PIN
#define BOARD_BUTTON3_PORT              GPIO_BUTTON_B_PORT
#define BOARD_BUTTON3_PIN               GPIO_BUTTON_B_BUTTON3_PIN
#define BOARD_BUTTON_ACTIVE_LOW         (1U)
#define BOARD_BUTTON_DEBOUNCE_MS        (20U)
#define BOARD_BUTTON_LONG_PRESS_MS      (800U)

/* LoRa 串口透传：PA14/UART3_TX 接 LoRa RX，PA13/UART3_RX 接 LoRa TX。 */
#define BOARD_LORA_UART_INST            LORA_UART_INST
#define BOARD_LORA_UART_IRQN            LORA_UART_INST_INT_IRQN
#define BOARD_LORA_TX_PORT              GPIO_LORA_UART_TX_PORT
#define BOARD_LORA_TX_PIN               GPIO_LORA_UART_TX_PIN
#define BOARD_LORA_RX_PORT              GPIO_LORA_UART_RX_PORT
#define BOARD_LORA_RX_PIN               GPIO_LORA_UART_RX_PIN
#define BOARD_LORA_BAUDRATE             (115200U)
#define BOARD_LORA_RX_BUFFER_SIZE       (256U)
#define BOARD_LORA_TX_TIMEOUT_ITERATIONS (100000U)

/* TCAN3413 on CANFD1: PC26/TX -> TXD, PC27/RX <- RXD, PC25 -> STB. */
#define BOARD_CAN_INST                   CAN_BUS_INST
#define BOARD_CAN_IRQN                   CAN_BUS_INST_INT_IRQN
#define BOARD_CAN_STB_PORT               GPIO_CAN_CTRL_PORT
#define BOARD_CAN_STB_PIN                GPIO_CAN_CTRL_CAN_STB_PIN
#define BOARD_CAN_BITRATE                (250000U)
#define BOARD_CAN_TX_BUFFER              (0U)
#define BOARD_CAN_RX_QUEUE_SIZE          (32U)
#define BOARD_CAN_IRQ_PRIORITY           (2U)

/* MotorDriver 串口连接测试：芯片封装 PA8/UART1_TX 接 MotorDriver RX，PA9/UART1_RX 接 MotorDriver TX。 */
#define BOARD_MOTOR_DRIVER_UART_INST            MOTOR_UART_INST
#define BOARD_MOTOR_DRIVER_UART_IRQN            MOTOR_UART_INST_INT_IRQN
#define BOARD_MOTOR_DRIVER_TX_PORT              GPIO_MOTOR_UART_TX_PORT
#define BOARD_MOTOR_DRIVER_TX_PIN               GPIO_MOTOR_UART_TX_PIN
#define BOARD_MOTOR_DRIVER_RX_PORT              GPIO_MOTOR_UART_RX_PORT
#define BOARD_MOTOR_DRIVER_RX_PIN               GPIO_MOTOR_UART_RX_PIN
#define BOARD_MOTOR_DRIVER_BAUDRATE             (115200U)
#define BOARD_MOTOR_DRIVER_RX_BUFFER_SIZE       (256U)
#define BOARD_MOTOR_DRIVER_TX_TIMEOUT_ITERATIONS (100000U)

/* MotorDriver I2C: board IIC1, PA11/SCL and PA10/SDA. */
#define BOARD_MOTOR_DRIVER_I2C_INST             MOTOR_I2C_INST
#define BOARD_MOTOR_DRIVER_I2C_SCL_PORT         GPIO_MOTOR_I2C_SCL_PORT
#define BOARD_MOTOR_DRIVER_I2C_SCL_PIN          GPIO_MOTOR_I2C_SCL_PIN
#define BOARD_MOTOR_DRIVER_I2C_SCL_IOMUX        GPIO_MOTOR_I2C_IOMUX_SCL
#define BOARD_MOTOR_DRIVER_I2C_SCL_IOMUX_FUNC   GPIO_MOTOR_I2C_IOMUX_SCL_FUNC
#define BOARD_MOTOR_DRIVER_I2C_SDA_PORT         GPIO_MOTOR_I2C_SDA_PORT
#define BOARD_MOTOR_DRIVER_I2C_SDA_PIN          GPIO_MOTOR_I2C_SDA_PIN
#define BOARD_MOTOR_DRIVER_I2C_SDA_IOMUX        GPIO_MOTOR_I2C_IOMUX_SDA
#define BOARD_MOTOR_DRIVER_I2C_SDA_IOMUX_FUNC   GPIO_MOTOR_I2C_IOMUX_SDA_FUNC
#define BOARD_MOTOR_DRIVER_I2C_ADDRESS          (0x20U)
#define BOARD_MOTOR_DRIVER_I2C_TIMEOUT_ITERATIONS (100000U)

#define BOARD_FRAM_I2C_INST             SENSOR_I2C_INST
#define BOARD_FRAM_I2C_SCL_PORT         GPIO_SENSOR_I2C_SCL_PORT
#define BOARD_FRAM_I2C_SCL_PIN          GPIO_SENSOR_I2C_SCL_PIN
#define BOARD_FRAM_I2C_SCL_IOMUX        GPIO_SENSOR_I2C_IOMUX_SCL
#define BOARD_FRAM_I2C_SCL_IOMUX_FUNC   GPIO_SENSOR_I2C_IOMUX_SCL_FUNC
#define BOARD_FRAM_I2C_SDA_PORT         GPIO_SENSOR_I2C_SDA_PORT
#define BOARD_FRAM_I2C_SDA_PIN          GPIO_SENSOR_I2C_SDA_PIN
#define BOARD_FRAM_I2C_SDA_IOMUX        GPIO_SENSOR_I2C_IOMUX_SDA
#define BOARD_FRAM_I2C_SDA_IOMUX_FUNC   GPIO_SENSOR_I2C_IOMUX_SDA_FUNC
#define BOARD_FRAM_I2C_ADDRESS          (0x50U)
#define BOARD_FRAM_TIMEOUT_ITERATIONS   (100000U)
#define BOARD_FRAM_SELF_TEST_ADDRESS    (0x1FF0U)

/* OLED shares board IIC3 with FRAM and INA219. Datasheet ADD=0x78 is 8-bit,
 * so firmware uses the 7-bit I2C address 0x3C. */
#define BOARD_OLED_I2C_BUS_NAME         "oled"
#define BOARD_OLED_I2C_INST             SENSOR_I2C_INST
#define BOARD_OLED_I2C_SCL_PORT         GPIO_SENSOR_I2C_SCL_PORT
#define BOARD_OLED_I2C_SCL_PIN          GPIO_SENSOR_I2C_SCL_PIN
#define BOARD_OLED_I2C_SCL_IOMUX        GPIO_SENSOR_I2C_IOMUX_SCL
#define BOARD_OLED_I2C_SCL_IOMUX_FUNC   GPIO_SENSOR_I2C_IOMUX_SCL_FUNC
#define BOARD_OLED_I2C_SDA_PORT         GPIO_SENSOR_I2C_SDA_PORT
#define BOARD_OLED_I2C_SDA_PIN          GPIO_SENSOR_I2C_SDA_PIN
#define BOARD_OLED_I2C_SDA_IOMUX        GPIO_SENSOR_I2C_IOMUX_SDA
#define BOARD_OLED_I2C_SDA_IOMUX_FUNC   GPIO_SENSOR_I2C_IOMUX_SDA_FUNC
#define BOARD_OLED_I2C_ADDRESS          (0x3CU)
#define BOARD_OLED_TIMEOUT_ITERATIONS   (100000U)
#define BOARD_OLED_DMA_TIMEOUT_MS       (50U)
#define BOARD_OLED_I2C_IRQ_PRIORITY     (3U)
#define BOARD_OLED_WIDTH                (128U)
#define BOARD_OLED_HEIGHT               (32U)

/* INA219 shares board IIC3 with FRAM; shunt resistor is 5 mR. */
#define BOARD_INA219_I2C_INST           SENSOR_I2C_INST
#define BOARD_INA219_I2C_SCL_PORT       GPIO_SENSOR_I2C_SCL_PORT
#define BOARD_INA219_I2C_SCL_PIN        GPIO_SENSOR_I2C_SCL_PIN
#define BOARD_INA219_I2C_SCL_IOMUX      GPIO_SENSOR_I2C_IOMUX_SCL
#define BOARD_INA219_I2C_SCL_IOMUX_FUNC GPIO_SENSOR_I2C_IOMUX_SCL_FUNC
#define BOARD_INA219_I2C_SDA_PORT       GPIO_SENSOR_I2C_SDA_PORT
#define BOARD_INA219_I2C_SDA_PIN        GPIO_SENSOR_I2C_SDA_PIN
#define BOARD_INA219_I2C_SDA_IOMUX      GPIO_SENSOR_I2C_IOMUX_SDA
#define BOARD_INA219_I2C_SDA_IOMUX_FUNC GPIO_SENSOR_I2C_IOMUX_SDA_FUNC
#define BOARD_INA219_I2C_ADDRESS        (0x40U)
#define BOARD_INA219_TIMEOUT_ITERATIONS (100000U)
#define BOARD_INA219_SHUNT_MILLIOHMS    (5U)
#define BOARD_INA219_CURRENT_LSB_UA     (200U)
/* 当前板子 IN+/IN- 方向与期望读数相反，软件取反后 shell 显示为正电流。 */
#define BOARD_INA219_INVERT_CURRENT     (1U)

#define BOARD_IMU_SPI_INST              IMU_SPI_INST
#define BOARD_IMU_SPI_IRQN              IMU_SPI_INST_INT_IRQN
#define BOARD_IMU_SPI_TIMEOUT_ITERATIONS (100000U)
#define BOARD_IMU_SPI_SCLK_PORT         GPIO_IMU_SPI_SCLK_PORT
#define BOARD_IMU_SPI_SCLK_PIN          GPIO_IMU_SPI_SCLK_PIN
#define BOARD_IMU_SPI_SCLK_IOMUX        GPIO_IMU_SPI_IOMUX_SCLK
#define BOARD_IMU_SPI_SCLK_IOMUX_FUNC   GPIO_IMU_SPI_IOMUX_SCLK_FUNC
#define BOARD_IMU_SPI_PICO_PORT         GPIO_IMU_SPI_PICO_PORT
#define BOARD_IMU_SPI_PICO_PIN          GPIO_IMU_SPI_PICO_PIN
#define BOARD_IMU_SPI_PICO_IOMUX        GPIO_IMU_SPI_IOMUX_PICO
#define BOARD_IMU_SPI_PICO_IOMUX_FUNC   GPIO_IMU_SPI_IOMUX_PICO_FUNC
#define BOARD_IMU_SPI_POCI_PORT         GPIO_IMU_SPI_POCI_PORT
#define BOARD_IMU_SPI_POCI_PIN          GPIO_IMU_SPI_POCI_PIN
#define BOARD_IMU_SPI_POCI_IOMUX        GPIO_IMU_SPI_IOMUX_POCI
#define BOARD_IMU_SPI_POCI_IOMUX_FUNC   GPIO_IMU_SPI_IOMUX_POCI_FUNC

#define BOARD_IMU_ICM45686_CS_PORT      GPIO_IMU_C_PORT
#define BOARD_IMU_ICM45686_CS_PIN       GPIO_IMU_C_ICM45686_CS_PIN
#define BOARD_IMU_LIS3MDL_CS_PORT       GPIO_IMU_C_PORT
#define BOARD_IMU_LIS3MDL_CS_PIN        GPIO_IMU_C_LIS3MDL_CS_PIN
#define BOARD_IMU_ICM45686_INT1_PORT    GPIO_IMU_C_PORT
#define BOARD_IMU_ICM45686_INT1_PIN     GPIO_IMU_C_ICM45686_INT1_PIN
#define BOARD_IMU_LIS3MDL_DRDY_PORT     GPIO_IMU_A_PORT
#define BOARD_IMU_LIS3MDL_DRDY_PIN      GPIO_IMU_A_LIS3MDL_DRDY_PIN
#define BOARD_IMU_ICM45686_INT2_FSYNC_PORT GPIO_IMU_A_PORT
#define BOARD_IMU_ICM45686_INT2_FSYNC_PIN  GPIO_IMU_A_ICM45686_INT2_FSYNC_PIN

/* 8-channel grayscale sensor: 3 select pins (PA16=bit2, PC20=bit1, PC21=bit0)
 * mux one of 8 phototransistor outputs to PA15 (ADC1 ADCIN0). */
#define BOARD_GRAYSCALE_ADC_INST          GRAYSCALE_ADC_INST
#define BOARD_GRAYSCALE_ADC_IRQN          GRAYSCALE_ADC_INST_INT_IRQN
#define BOARD_GRAYSCALE_ADC_MEM_IDX       DL_ADC12_MEM_IDX_0
#define BOARD_GRAYSCALE_ADC_RESULT_MASK   DL_ADC12_INTERRUPT_MEM0_RESULT_LOADED
#define BOARD_GRAYSCALE_SEL0_PORT         GPIO_GRAY_C_PORT
#define BOARD_GRAYSCALE_SEL0_PIN          GPIO_GRAY_C_GRAY_SEL0_PIN
#define BOARD_GRAYSCALE_SEL1_PORT         GPIO_GRAY_C_PORT
#define BOARD_GRAYSCALE_SEL1_PIN          GPIO_GRAY_C_GRAY_SEL1_PIN
#define BOARD_GRAYSCALE_SEL2_PORT         GPIO_GRAY_A_PORT
#define BOARD_GRAYSCALE_SEL2_PIN          GPIO_GRAY_A_GRAY_SEL2_PIN
#define BOARD_GRAYSCALE_SETTLE_US         (200U)
#define BOARD_GRAYSCALE_ADC_TIMEOUT_US    (1000U)
#define BOARD_GRAYSCALE_ADC_TIMEOUT       (100000U)

#endif /* BOARD_BOARD_PINS_H_ */
