#ifndef BOARD_BOARD_ENCODER_PINS_H_
#define BOARD_BOARD_ENCODER_PINS_H_

#include "ti_msp_dl_config.h"

namespace board {

#define BOARD_M1_ENC_A_PORT GPIOB
#define BOARD_M1_ENC_A_PIN GPIO_ENCODER_M1_ENC_A_PIN
#define BOARD_M1_ENC_A_IOMUX GPIO_ENCODER_M1_ENC_A_IOMUX

#define BOARD_M1_ENC_B_PORT GPIOB
#define BOARD_M1_ENC_B_PIN GPIO_ENCODER_M1_ENC_B_PIN
#define BOARD_M1_ENC_B_IOMUX GPIO_ENCODER_M1_ENC_B_IOMUX

#define BOARD_M2_ENC_A_PORT GPIOA
#define BOARD_M2_ENC_A_PIN GPIO_ENCODER_M2_ENC_A_PIN
#define BOARD_M2_ENC_A_IOMUX GPIO_ENCODER_M2_ENC_A_IOMUX

#define BOARD_M2_ENC_B_PORT GPIOA
#define BOARD_M2_ENC_B_PIN GPIO_ENCODER_M2_ENC_B_PIN
#define BOARD_M2_ENC_B_IOMUX GPIO_ENCODER_M2_ENC_B_IOMUX

#define BOARD_M1_EDGE_COUNTER_INST TIMG6
#define BOARD_M1_EDGE_COUNTER_IOMUX_FUNC IOMUX_PINCM24_PF_TIMG6_CCP1
#define BOARD_M1_EDGE_COUNTER_INPUT_CHAN DL_TIMER_INPUT_CHAN_1

#define BOARD_M2_QEI_INST TIMG8
#define BOARD_M2_QEI_PHA_IOMUX BOARD_M2_ENC_B_IOMUX
#define BOARD_M2_QEI_PHA_IOMUX_FUNC IOMUX_PINCM46_PF_TIMG8_CCP0
#define BOARD_M2_QEI_PHB_IOMUX BOARD_M2_ENC_A_IOMUX
#define BOARD_M2_QEI_PHB_IOMUX_FUNC IOMUX_PINCM47_PF_TIMG8_CCP1

#define BOARD_ENCODER_IRQN GPIOA_INT_IRQn

constexpr int8_t kM2QeiCountSign = -1;
constexpr uint32_t kEncoderSamplePeriodMs = 50U;

}  // namespace board

#endif  // BOARD_BOARD_ENCODER_PINS_H_
