#ifndef BOARD_BOARD_MOTOR_PINS_H_
#define BOARD_BOARD_MOTOR_PINS_H_

#include <stdint.h>

#include "ti_msp_dl_config.h"

namespace board {

constexpr uint32_t kMotorPwmPeriodCounts = 1600U;
constexpr uint32_t kUartTxTimeoutIterations = 100000U;
constexpr uint16_t kUartRxBufferSize = 256U;
constexpr uint8_t kI2cTargetAddress = 0x20U;

#define BOARD_M1_PH_PORT GPIO_M1_PH_PORT
#define BOARD_M1_PH_PIN GPIO_M1_PH_M1_PH_PIN

#define BOARD_M2_PH_PORT GPIO_M2_PH_PORT
#define BOARD_M2_PH_PIN GPIO_M2_PH_M2_PH_PIN

#define BOARD_M1_PWM_INST PWM_M1_EN_INST
#define BOARD_M1_PWM_PORT GPIO_PWM_M1_EN_C1_PORT
#define BOARD_M1_PWM_PIN GPIO_PWM_M1_EN_C1_PIN
#define BOARD_M1_PWM_IOMUX GPIO_PWM_M1_EN_C1_IOMUX
#define BOARD_M1_PWM_IOMUX_FUNC GPIO_PWM_M1_EN_C1_IOMUX_FUNC
#define BOARD_M1_PWM_INDEX GPIO_PWM_M1_EN_C1_IDX

#define BOARD_M2_PWM_INST PWM_M2_EN_INST
#define BOARD_M2_PWM_PORT GPIO_PWM_M2_EN_C1_PORT
#define BOARD_M2_PWM_PIN GPIO_PWM_M2_EN_C1_PIN
#define BOARD_M2_PWM_IOMUX GPIO_PWM_M2_EN_C1_IOMUX
#define BOARD_M2_PWM_IOMUX_FUNC GPIO_PWM_M2_EN_C1_IOMUX_FUNC
#define BOARD_M2_PWM_INDEX GPIO_PWM_M2_EN_C1_IDX

#define BOARD_UART_INST UART_CONTROL_INST
#define BOARD_UART_IRQN UART_CONTROL_INST_INT_IRQN
#define BOARD_UART_RX_IOMUX GPIO_UART_CONTROL_IOMUX_RX
#define BOARD_UART_RX_IOMUX_FUNC GPIO_UART_CONTROL_IOMUX_RX_FUNC

#define BOARD_I2C_INST I2C_CONTROL_INST
#define BOARD_I2C_IRQN I2C_CONTROL_INST_INT_IRQN
#define BOARD_I2C_SDA_IOMUX GPIO_I2C_CONTROL_IOMUX_SDA
#define BOARD_I2C_SDA_IOMUX_FUNC GPIO_I2C_CONTROL_IOMUX_SDA_FUNC
#define BOARD_I2C_SDA_PORT GPIO_I2C_CONTROL_SDA_PORT
#define BOARD_I2C_SDA_PIN GPIO_I2C_CONTROL_SDA_PIN
#define BOARD_I2C_SCL_IOMUX GPIO_I2C_CONTROL_IOMUX_SCL
#define BOARD_I2C_SCL_IOMUX_FUNC GPIO_I2C_CONTROL_IOMUX_SCL_FUNC
#define BOARD_I2C_SCL_PORT GPIO_I2C_CONTROL_SCL_PORT
#define BOARD_I2C_SCL_PIN GPIO_I2C_CONTROL_SCL_PIN

}  // namespace board

#endif  // BOARD_BOARD_MOTOR_PINS_H_
