#ifndef BOARD_BOARD_ENCODER_PINS_H_
#define BOARD_BOARD_ENCODER_PINS_H_

#include "ti_msp_dl_config.h"

namespace board {

#define BOARD_M1_ENC_A_PORT GPIOB
#define BOARD_M1_ENC_A_PIN GPIO_ENCODER_M1_ENC_A_PIN
#define BOARD_M1_ENC_A_IOMUX GPIO_ENCODER_M1_ENC_A_IOMUX

#define BOARD_M1_ENC_B_PORT GPIOB
#define BOARD_M1_ENC_B_PIN GPIO_ENCODER_M1_ENC_B_PIN
#define BOARD_M1_ENC_B_IOMUX GPIO_ENCODER_M1_ENC_B_IOMUX

#define BOARD_M2_ENC_A_PORT GPIOA
#define BOARD_M2_ENC_A_PIN GPIO_ENCODER_M2_ENC_A_PIN
#define BOARD_M2_ENC_A_IOMUX GPIO_ENCODER_M2_ENC_A_IOMUX

#define BOARD_M2_ENC_B_PORT GPIOA
#define BOARD_M2_ENC_B_PIN GPIO_ENCODER_M2_ENC_B_PIN
#define BOARD_M2_ENC_B_IOMUX GPIO_ENCODER_M2_ENC_B_IOMUX

#define BOARD_ENCODER_IRQN GPIOA_INT_IRQn

constexpr uint32_t kEncoderSamplePeriodMs = 100U;

}  // namespace board

#endif  // BOARD_BOARD_ENCODER_PINS_H_
