#ifndef GUGAH_BOARD_BOARD_PINS_H_
#define GUGAH_BOARD_BOARD_PINS_H_

#include "ti_msp_dl_config.h"

#define BOARD_LED_COUNT                 (3U)
#define BOARD_LED1_PORT                 GPIO_LED_A_PORT
#define BOARD_LED1_PIN                  GPIO_LED_A_LED1_PIN
#define BOARD_LED1_ACTIVE_LOW           (1U)
#define BOARD_LED1_INITIAL_ON           (0U)
#define BOARD_LED2_PORT                 GPIO_LED_A_PORT
#define BOARD_LED2_PIN                  GPIO_LED_A_LED2_PIN
#define BOARD_LED2_ACTIVE_LOW           (1U)
#define BOARD_LED2_INITIAL_ON           (0U)
#define BOARD_LED3_PORT                 GPIO_LED_B_PORT
#define BOARD_LED3_PIN                  GPIO_LED_B_LED3_PIN
#define BOARD_LED3_ACTIVE_LOW           (1U)
#define BOARD_LED3_INITIAL_ON           (0U)
#define BOARD_STATUS_LED_PORT           BOARD_LED1_PORT
#define BOARD_STATUS_LED_PIN            BOARD_LED1_PIN
#define BOARD_STATUS_LED_ACTIVE_LOW     BOARD_LED1_ACTIVE_LOW
#define BOARD_STATUS_LED_INITIAL_ON     BOARD_LED1_INITIAL_ON

#define BOARD_BUZZER_PORT               GPIO_BUZZER_PORT
#define BOARD_BUZZER_PIN                GPIO_BUZZER_BUZZER_PIN
#define BOARD_BUZZER_ACTIVE_HIGH        (1U)
#define BOARD_BUZZER_INITIAL_ON         (0U)

#define BOARD_BUTTON1_PORT              GPIO_BUTTON_C_PORT
#define BOARD_BUTTON1_PIN               GPIO_BUTTON_C_BUTTON1_PIN
#define BOARD_BUTTON2_PORT              GPIO_BUTTON_B_PORT
#define BOARD_BUTTON2_PIN               GPIO_BUTTON_B_BUTTON2_PIN
#define BOARD_BUTTON3_PORT              GPIO_BUTTON_B_PORT
#define BOARD_BUTTON3_PIN               GPIO_BUTTON_B_BUTTON3_PIN
#define BOARD_BUTTON_ACTIVE_LOW         (1U)
#define BOARD_BUTTON_DEBOUNCE_MS        (20U)
#define BOARD_BUTTON_LONG_PRESS_MS      (800U)

#define BOARD_BALL_VISION_UART_INST      BALL_VISION_UART_INST
#define BOARD_BALL_VISION_UART_IRQN      BALL_VISION_UART_INST_INT_IRQN
#define BOARD_BALL_VISION_RX_BUFFER_SIZE (256U)

#define BOARD_CAN_INST                   CAN_BUS_INST
#define BOARD_CAN_IRQN                   CAN_BUS_INST_INT_IRQN
#define BOARD_CAN_STB_PORT               GPIO_CAN_CTRL_PORT
#define BOARD_CAN_STB_PIN                GPIO_CAN_CTRL_CAN_STB_PIN
#define BOARD_CAN_BITRATE                (250000U)
#define BOARD_CAN_TX_BUFFER              (0U)
#define BOARD_CAN_RX_QUEUE_SIZE          (16U)
#define BOARD_CAN_IRQ_PRIORITY           (2U)

#define BOARD_MOTOR_I2C_INST             MOTOR_I2C_INST
#define BOARD_MOTOR_I2C_ADDRESS          (0x20U)
#define BOARD_MOTOR_I2C_TIMEOUT          (100000U)
#define BOARD_MOTOR_I2C_SCL_PORT         GPIO_MOTOR_I2C_SCL_PORT
#define BOARD_MOTOR_I2C_SCL_PIN          GPIO_MOTOR_I2C_SCL_PIN
#define BOARD_MOTOR_I2C_SCL_IOMUX        GPIO_MOTOR_I2C_IOMUX_SCL
#define BOARD_MOTOR_I2C_SCL_IOMUX_FUNC   GPIO_MOTOR_I2C_IOMUX_SCL_FUNC
#define BOARD_MOTOR_I2C_SDA_PORT         GPIO_MOTOR_I2C_SDA_PORT
#define BOARD_MOTOR_I2C_SDA_PIN          GPIO_MOTOR_I2C_SDA_PIN
#define BOARD_MOTOR_I2C_SDA_IOMUX        GPIO_MOTOR_I2C_IOMUX_SDA
#define BOARD_MOTOR_I2C_SDA_IOMUX_FUNC   GPIO_MOTOR_I2C_IOMUX_SDA_FUNC

#define BOARD_SENSOR_I2C_INST            SENSOR_I2C_INST
#define BOARD_SENSOR_I2C_TIMEOUT         (100000U)
#define BOARD_SENSOR_I2C_SCL_PORT        GPIO_SENSOR_I2C_SCL_PORT
#define BOARD_SENSOR_I2C_SCL_PIN         GPIO_SENSOR_I2C_SCL_PIN
#define BOARD_SENSOR_I2C_SCL_IOMUX       GPIO_SENSOR_I2C_IOMUX_SCL
#define BOARD_SENSOR_I2C_SCL_IOMUX_FUNC  GPIO_SENSOR_I2C_IOMUX_SCL_FUNC
#define BOARD_SENSOR_I2C_SDA_PORT        GPIO_SENSOR_I2C_SDA_PORT
#define BOARD_SENSOR_I2C_SDA_PIN         GPIO_SENSOR_I2C_SDA_PIN
#define BOARD_SENSOR_I2C_SDA_IOMUX       GPIO_SENSOR_I2C_IOMUX_SDA
#define BOARD_SENSOR_I2C_SDA_IOMUX_FUNC  GPIO_SENSOR_I2C_IOMUX_SDA_FUNC

#define BOARD_FRAM_I2C_INST              BOARD_SENSOR_I2C_INST
#define BOARD_FRAM_I2C_ADDRESS           (0x50U)
#define BOARD_FRAM_TIMEOUT_ITERATIONS    BOARD_SENSOR_I2C_TIMEOUT
#define BOARD_FRAM_SELF_TEST_ADDRESS     (0x1FF8U)
#define BOARD_FRAM_I2C_SCL_PORT          BOARD_SENSOR_I2C_SCL_PORT
#define BOARD_FRAM_I2C_SCL_PIN           BOARD_SENSOR_I2C_SCL_PIN
#define BOARD_FRAM_I2C_SCL_IOMUX         BOARD_SENSOR_I2C_SCL_IOMUX
#define BOARD_FRAM_I2C_SCL_IOMUX_FUNC    BOARD_SENSOR_I2C_SCL_IOMUX_FUNC
#define BOARD_FRAM_I2C_SDA_PORT          BOARD_SENSOR_I2C_SDA_PORT
#define BOARD_FRAM_I2C_SDA_PIN           BOARD_SENSOR_I2C_SDA_PIN
#define BOARD_FRAM_I2C_SDA_IOMUX         BOARD_SENSOR_I2C_SDA_IOMUX
#define BOARD_FRAM_I2C_SDA_IOMUX_FUNC    BOARD_SENSOR_I2C_SDA_IOMUX_FUNC

#define BOARD_OLED_I2C_BUS_NAME          "oled"
#define BOARD_OLED_I2C_INST              BOARD_SENSOR_I2C_INST
#define BOARD_OLED_I2C_ADDRESS           (0x3CU)
#define BOARD_OLED_TIMEOUT_ITERATIONS    BOARD_SENSOR_I2C_TIMEOUT
#define BOARD_OLED_DMA_TIMEOUT_MS        (50U)
#define BOARD_OLED_I2C_IRQ_PRIORITY      (3U)
#define BOARD_OLED_WIDTH                 (128U)
#define BOARD_OLED_HEIGHT                (32U)
#define BOARD_OLED_I2C_SCL_PORT          BOARD_SENSOR_I2C_SCL_PORT
#define BOARD_OLED_I2C_SCL_PIN           BOARD_SENSOR_I2C_SCL_PIN
#define BOARD_OLED_I2C_SCL_IOMUX         BOARD_SENSOR_I2C_SCL_IOMUX
#define BOARD_OLED_I2C_SCL_IOMUX_FUNC    BOARD_SENSOR_I2C_SCL_IOMUX_FUNC
#define BOARD_OLED_I2C_SDA_PORT          BOARD_SENSOR_I2C_SDA_PORT
#define BOARD_OLED_I2C_SDA_PIN           BOARD_SENSOR_I2C_SDA_PIN
#define BOARD_OLED_I2C_SDA_IOMUX         BOARD_SENSOR_I2C_SDA_IOMUX
#define BOARD_OLED_I2C_SDA_IOMUX_FUNC    BOARD_SENSOR_I2C_SDA_IOMUX_FUNC

#define BOARD_IMU_SPI_INST               IMU_SPI_INST
#define BOARD_IMU_SPI_TIMEOUT_ITERATIONS (100000U)
#define BOARD_IMU_CS_PORT                GPIO_IMU_C_PORT
#define BOARD_IMU_CS_PIN                 GPIO_IMU_C_ICM45686_CS_PIN

#define BOARD_GRAYSCALE_ADC_INST         GRAYSCALE_ADC_INST
#define BOARD_GRAYSCALE_ADC_IRQN         GRAYSCALE_ADC_INST_INT_IRQN
#define BOARD_GRAYSCALE_ADC_MEM_IDX      DL_ADC12_MEM_IDX_0
#define BOARD_GRAYSCALE_ADC_RESULT_MASK  DL_ADC12_INTERRUPT_MEM0_RESULT_LOADED
#define BOARD_GRAYSCALE_SEL0_PORT        GPIO_GRAY_C_PORT
#define BOARD_GRAYSCALE_SEL0_PIN         GPIO_GRAY_C_GRAY_SEL0_PIN
#define BOARD_GRAYSCALE_SEL1_PORT        GPIO_GRAY_C_PORT
#define BOARD_GRAYSCALE_SEL1_PIN         GPIO_GRAY_C_GRAY_SEL1_PIN
#define BOARD_GRAYSCALE_SEL2_PORT        GPIO_GRAY_A_PORT
#define BOARD_GRAYSCALE_SEL2_PIN         GPIO_GRAY_A_GRAY_SEL2_PIN
#define BOARD_GRAYSCALE_SETTLE_US        (200U)
#define BOARD_GRAYSCALE_ADC_TIMEOUT_US   (1000U)
#define BOARD_GRAYSCALE_ADC_TIMEOUT      (100000U)

#endif /* GUGAH_BOARD_BOARD_PINS_H_ */
